# Generated by Django 3.2 on 2021-04-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_rename_contact_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='loc_image',
            field=models.ImageField(blank=True, null=True, upload_to='icon/'),
        ),
    ]
