# Generated by Django 3.2 on 2021-04-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0004_auto_20210413_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='keywords',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='detail',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='update_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not available', 'Not available')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
